######################################################################
# Automatically generated by qmake (3.0) ?? 10? 13 10:11:28 2015
######################################################################

TARGET = warning
INCLUDEPATH += .

#QT += core gui network opengl qml quick 
QT += core gui network opengl qml quick 

CONFIG += debug 

CONFIG += qt
CONFIG += warn_off
CONFIG += thread
CONFIG += c++11
CONFIG += static

# Input
SOURCES += warning.cpp
RESOURCES += resources.qrc
