######################################################################
# Automatically generated by qmake (3.0) ?? 10? 13 10:11:28 2015
######################################################################

TARGET = quickpainteditemswap
INCLUDEPATH += .

QT += core gui network opengl qml quick svg xml widgets dbus testlib

CONFIG += debug 

CONFIG += qt
CONFIG += warn_off
CONFIG += thread
CONFIG += c++11
CONFIG += static

# Input
HEADERS += myimage.h
SOURCES += main.cpp myimage.cpp
