######################################################################
# Automatically generated by qmake (3.0) ?? 10? 13 10:11:28 2015
######################################################################

TEMPLATE = subdirs
SUBDIRS = simulateClick simulateAuto

