######################################################################
# Automatically generated by qmake (3.0) ?? 10? 13 10:11:28 2015
######################################################################

TARGET = sample1
INCLUDEPATH += .

#QT += core gui network opengl qml quick 
QT += core gui qml  

CONFIG += debug 
CONFIG += qt
CONFIG += c++11
CONFIG += static

# Input
SOURCES += sample1.cpp
